/*
 * This source file was generated by the Gradle 'init' task
 */
package com.willtkelly;

import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;

public class App {

    public static void main(String[] args) {

        if (args.length == 0) {
            System.out.println("Please include rom name... ( roms/[rom_name].ch8 )");
            return;
        }

        String rom = args[0];
        System.out.println(rom);

        Chip8 chip = new Chip8(rom);

        int resolution_scale = 10;
        int resolution_width = 64 * resolution_scale;
        int resolution_height = 32 * resolution_scale;

        Display display = new Display();
        Keyboard keyboard = new Keyboard();
        chip.setDisplay(display);
        chip.setKeyboard(keyboard);
        display.setChip(chip);

        Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
        config.setTitle("CHIP-8 Emulator");
        config.setWindowedMode(resolution_width, resolution_height);
        new Lwjgl3Application(display, config);
    }
}
